language: ruby
sudo: false
env:
  - DB=sqlite
bundler_args: --without development debug
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake test:all
services:
  - redis-server
notifications:
  email:
    - travis-notifications@fairmondo.de
before_install:
  - curl -k -L -o elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.tar.gz
  - tar -zxvf elasticsearch.tar.gz
  - ./elasticsearch-5.4.0/bin/elasticsearch-plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/5.4.0.0/elasticsearch-plugin-bundle-5.4.0.0-plugin.zip
  - ./elasticsearch-5.4.0/bin/elasticsearch &
  - cp config/secrets.yml.example config/secrets.yml
addons:
  apt:
    packages:
      - libssl1.0.0
      - openssl
      - ca-certificates
